name: Go Test

on:
  push:
    branches: 
      - master
    paths:
      - "**/*.go"
      - "**/*.s"
      - "**/*.yml"
      - "go.mod"
      - "go.sum"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Run Tests
      run: go test $(go list ./... | grep -v verthash)